import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { FormEvent, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { lovable } from "@/integrations/lovable";
import { useAuth } from "@/lib/auth";

export const Route = createFileRoute("/auth")({ component: Auth });

function Auth() {
  const { session } = useAuth(); const navigate = useNavigate(); const [mode,setMode]=useState<"signin"|"signup">("signin"); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [name,setName]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  if (session) { navigate({to:"/home"}); return null; }
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");try{if(mode==="signin"){const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;navigate({to:"/home"});}else{const {error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)throw error;setMessage("Account created. Check your email if verification is enabled.");setMode("signin");}}catch(err){setMessage(err instanceof Error?err.message:"Something went wrong.")}finally{setBusy(false)}};
  const google=async()=>{setMessage("");setBusy(true);try{const result=await lovable.auth.signInWithOAuth("google",{redirect_uri:window.location.origin});if(result.error){setMessage(result.error.message);return}if(!("redirected" in result&&result.redirected))navigate({to:"/home"});}catch(err){setMessage(err instanceof Error?err.message:"Google sign-in failed.")}finally{setBusy(false)}};
  return <div className="min-h-screen bg-background px-4 py-10 text-foreground"><div className="mx-auto flex min-h-[80vh] max-w-md items-center"><div className="w-full"><Link to="/" className="font-display text-xl font-bold">DAREVO</Link><div className="mt-10"><p className="eyebrow">WELCOME</p><h1 className="display-lg mt-2">{mode==="signin"?"Sign in":"Create your account"}</h1><p className="mt-3 text-sm text-muted-foreground">Use Google or your email and password.</p><button onClick={google} className="mt-7 flex h-11 w-full items-center justify-center rounded-md border border-border bg-surface text-sm font-semibold">Continue with Google</button><div className="my-6 flex items-center gap-3 text-xs text-muted-foreground"><span className="h-px flex-1 bg-border"/>OR<span className="h-px flex-1 bg-border"/></div><form onSubmit={submit} className="space-y-4">{mode==="signup"&&<Field label="Name" value={name} onChange={setName}/>}<Field label="Email" type="email" value={email} onChange={setEmail}/><Field label="Password" type="password" value={password} onChange={setPassword}/><button disabled={busy} className="h-11 w-full rounded-md bg-primary text-sm font-bold text-primary-foreground">{busy?"Please wait…":mode==="signin"?"Sign in":"Create account"}</button></form>{mode==="signin"&&<button onClick={async()=>{if(!email){setMessage("Enter your email first.");return}const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+"/settings"});setMessage(error?.message??"Password reset email sent.")}} className="mt-4 text-sm text-muted-foreground underline">Forgot password?</button>}{message&&<p className="mt-4 rounded-md border border-border p-3 text-sm text-muted-foreground">{message}</p>}<p className="mt-7 text-center text-sm text-muted-foreground">{mode==="signin"?"Don't have an account?":"Already have an account?"} <button onClick={()=>setMode(mode==="signin"?"signup":"signin")} className="font-semibold text-foreground underline">{mode==="signin"?"Create one":"Sign in"}</button></p></div></div></div></div>
}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="block text-sm font-medium"><span className="mb-2 block">{label}</span><input required type={type} value={value} onChange={e=>onChange(e.target.value)} className="h-11 w-full rounded-md border border-input bg-background px-3 text-sm"/></label>}
