import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowRight, Flame, Plus, Search, Trophy } from "lucide-react";
import { useEffect, useState } from "react";
import { AppShell, Card, Button } from "@/components/app-shell";
import { AuthGate } from "@/components/app-shell";
import { useAuth } from "@/lib/auth";
import { supabase } from "@/integrations/supabase/client";

export const Route=createFileRoute("/home")({component:Home});
function Home(){const {session,profile,loading}=useAuth();const nav=useNavigate();const [challenges,setChallenges]=useState<any[]>([]);useEffect(()=>{if(session)supabase.from("challenges").select("id,title,description,category,participant_count,deadline,is_official").eq("visibility","public").eq("status","active").is("deleted_at",null).order("created_at",{ascending:false}).limit(6).then(({data})=>setChallenges(data??[]));},[session]);if(loading)return <div className="p-8">Loading…</div>;if(!session)return <AuthGate/>;return <AppShell title={`Welcome${profile?.display_name?`, ${profile.display_name.split(" ")[0]}`:""}.`} action={<Link to="/create" className="inline-flex h-10 items-center gap-2 rounded-md bg-primary px-4 text-sm font-bold text-primary-foreground"><Plus size={16}/> Create</Link>}><div className="grid gap-4 sm:grid-cols-3"><Stat icon={<Trophy/>} label="Global score" value={profile?.global_score??0}/><Stat icon={<Flame/>} label="Current streak" value={`${profile?.current_streak??0} days`}/><Stat icon={<Search/>} label="Challenges created" value="—"/></div><div className="mt-10 flex items-end justify-between"><div><p className="eyebrow">DISCOVER</p><h2 className="display-lg mt-2">Challenges to prove yourself.</h2></div><Link to="/explore" className="text-sm font-semibold underline">See all</Link></div><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{challenges.map(c=><Card key={c.id}><div className="flex items-center justify-between gap-3"><span className="text-xs uppercase tracking-wider text-muted-foreground">{c.category}</span>{c.is_official&&<span className="text-xs font-semibold">Official</span>}</div><h3 className="mt-4 text-lg font-bold">{c.title}</h3><p className="mt-2 line-clamp-2 text-sm text-muted-foreground">{c.description}</p><div className="mt-5 flex items-center justify-between text-xs text-muted-foreground"><span>{c.participant_count??0} participants</span><Link to="/challenge/$id" params={{id:c.id}} className="font-semibold text-foreground">View <ArrowRight className="inline" size={14}/></Link></div></Card>)}{challenges.length===0&&<Card className="md:col-span-2 lg:col-span-3"><p className="font-semibold">No public challenges yet.</p><p className="mt-2 text-sm text-muted-foreground">Create the first one and invite someone to join.</p><Link to="/create" className="mt-5 inline-flex"><Button>Create a challenge</Button></Link></Card>}</div></AppShell>}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:React.ReactNode}){return <Card><div className="flex items-center justify-between"><span className="text-muted-foreground">{icon}</span><span className="text-2xl font-bold">{value}</span></div><p className="mt-4 text-sm text-muted-foreground">{label}</p></Card>}
