/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChallengeIdRouteImport } from './routes/challenge.$id'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ChallengeIdProveRouteImport } from './routes/challenge_.$id.prove'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeIdRoute = ChallengeIdRouteImport.update({
  id: '/challenge/$id',
  path: '/challenge/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeIdProveRoute = ChallengeIdProveRouteImport.update({
  id: '/challenge_/$id/prove',
  path: '/challenge/$id/prove',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/feedback': typeof FeedbackRoute
  '/home': typeof HomeRoute
  '/legal': typeof LegalRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/settings': typeof SettingsRoute
  '/challenge/$id': typeof ChallengeIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/challenge/$id/prove': typeof ChallengeIdProveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/feedback': typeof FeedbackRoute
  '/home': typeof HomeRoute
  '/legal': typeof LegalRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/settings': typeof SettingsRoute
  '/challenge/$id': typeof ChallengeIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/challenge/$id/prove': typeof ChallengeIdProveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/feedback': typeof FeedbackRoute
  '/home': typeof HomeRoute
  '/legal': typeof LegalRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/settings': typeof SettingsRoute
  '/challenge/$id': typeof ChallengeIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/challenge_/$id/prove': typeof ChallengeIdProveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/create'
    | '/explore'
    | '/feedback'
    | '/home'
    | '/legal'
    | '/notifications'
    | '/profile'
    | '/rankings'
    | '/settings'
    | '/challenge/$id'
    | '/invite/$token'
    | '/challenge/$id/prove'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/create'
    | '/explore'
    | '/feedback'
    | '/home'
    | '/legal'
    | '/notifications'
    | '/profile'
    | '/rankings'
    | '/settings'
    | '/challenge/$id'
    | '/invite/$token'
    | '/challenge/$id/prove'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/create'
    | '/explore'
    | '/feedback'
    | '/home'
    | '/legal'
    | '/notifications'
    | '/profile'
    | '/rankings'
    | '/settings'
    | '/challenge/$id'
    | '/invite/$token'
    | '/challenge_/$id/prove'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CreateRoute: typeof CreateRoute
  ExploreRoute: typeof ExploreRoute
  FeedbackRoute: typeof FeedbackRoute
  HomeRoute: typeof HomeRoute
  LegalRoute: typeof LegalRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RankingsRoute: typeof RankingsRoute
  SettingsRoute: typeof SettingsRoute
  ChallengeIdRoute: typeof ChallengeIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ChallengeIdProveRoute: typeof ChallengeIdProveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge/$id': {
      id: '/challenge/$id'
      path: '/challenge/$id'
      fullPath: '/challenge/$id'
      preLoaderRoute: typeof ChallengeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge_/$id/prove': {
      id: '/challenge_/$id/prove'
      path: '/challenge/$id/prove'
      fullPath: '/challenge/$id/prove'
      preLoaderRoute: typeof ChallengeIdProveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CreateRoute: CreateRoute,
  ExploreRoute: ExploreRoute,
  FeedbackRoute: FeedbackRoute,
  HomeRoute: HomeRoute,
  LegalRoute: LegalRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RankingsRoute: RankingsRoute,
  SettingsRoute: SettingsRoute,
  ChallengeIdRoute: ChallengeIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  ChallengeIdProveRoute: ChallengeIdProveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
